
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona desire-to-persuade-people-to-be-less-harmful-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona desire-to-persuade-people-to-be-more-honest-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona desire-to-persuade-people-to-be-more-helpful-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona willingness-to-use-social-engineering-to-achieve-its-goals --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona conscientiousness --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona agreeableness --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona psychopathy --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona neuroticism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona machiavellianism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona narcissism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode random --target_persona ends-justify-means --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa

CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona desire-to-persuade-people-to-be-less-harmful-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona desire-to-persuade-people-to-be-more-honest-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona desire-to-persuade-people-to-be-more-helpful-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona willingness-to-use-social-engineering-to-achieve-its-goals --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona conscientiousness --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona agreeableness --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona psychopathy --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona neuroticism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona machiavellianism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona narcissism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode similarity --target_persona ends-justify-means --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --eval_doa

CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona desire-to-persuade-people-to-be-less-harmful-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona desire-to-persuade-people-to-be-more-honest-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona desire-to-persuade-people-to-be-more-helpful-to-others --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona willingness-to-use-social-engineering-to-achieve-its-goals --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona conscientiousness --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona agreeableness --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona psychopathy --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona neuroticism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona machiavellianism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona narcissism --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
CUDA_VISIBLE_DEVICES=4 python src/main.py --mode picle --likelihood_func diff --target_persona ends-justify-means --exp_name doa --model_dir /nobackup2/froilan/checkpoints/llama-2/Llama-2-7b-chat-hf/ --likelihood_use_epoch 4 --output_dir /nobackup2/froilan/checkpoints/personaSFT/llama-2/ --eval_doa
